### ISSUE TITLE
Config Page Displays Incorrectly

### ISSUE THREAD

**Issue by gaorocks** [haishanh/yacd#12] opened 2019-04-06 18:15 UTC
It seems like the config page just shows default settings (e.g., Mode: Rule, Log Level: Info) during page initialization. It won't render any actual data fetched from clash until you change something by clicking on any button/switch. I remembered it used to be working properly last time.

**Comment by haishanh** [comment] 2019-04-18 14:51
Thanks for reporting.

There is a bug indeed, should've been fixed with https://github.com/haishanh/yacd/commit/68a38e735945edc6878557c8f0c745f8f5f70023

I'm closing this. Feel free to reopen if the issue is still there.

**Closed by haishanh** 2019-04-18 14:51 UTC

**Comment by gaorocks** [comment] 2019-04-18 16:06
I've tested and it's come back to normal behavior. Thanks for your effort spent. Much appreciated.
